services:
  flask-api: # host name
    build: ./api
    restart: always
    depends_on: 
      - mlflow-server
    ports:
      - "5001:5001"
    volumes:
      - "./mlruns:/mlflow"
    environment:
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    
  mlflow-server:
    build: ./app
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - "./mlruns:/mlflow" # Volume for MLflow to store experiment data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: 
      mlflow server --backend-store-uri sqlite:////mlflow/mlflow.db --default-artifact-root /mlflow/artifacts --host 0.0.0.0
